# Generated by Django 3.2.6 on 2021-11-29 23:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categoria_comentarios_listado_pujas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('pujaActual', models.FloatField()),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('TEC', 'Tecnologia'), ('DEP', 'Deportes'), ('ALI', 'Alimentos'), ('VES', 'Vestimenta'), ('LIB', 'Libros'), ('AUT', 'Autos'), ('GAM', 'Gaming'), ('NON', 'Ninguna')], default='NON', max_length=3)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('estadoCerrado', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.FloatField()),
                ('fechaOferta', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='pujas',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='pujas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fechaComentario',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 29, 23, 23, 29, 302052, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Listado',
        ),
        migrations.DeleteModel(
            name='Pujas',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='auction',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
    ]
